INSERT INTO PUBLIC.specialization(name) VALUES ('Аллерголог');
INSERT INTO PUBLIC.specialization(name) VALUES ('Диетолог');
INSERT INTO PUBLIC.specialization(name) VALUES ('Психиатр');
INSERT INTO PUBLIC.specialization(name) VALUES ('Стоматолог');
INSERT INTO PUBLIC.specialization(name) VALUES ('Терапевт');
INSERT INTO PUBLIC.doctor(name, surname, patronymic, specialization_id) VALUES ('Анатолий', 'Анатольев', 'Анатольевич', 0);
INSERT INTO PUBLIC.doctor(name, surname, patronymic, specialization_id) VALUES ('Геннадий', 'Геннадьев', 'Геннадьевич', 1);
INSERT INTO PUBLIC.doctor(name, surname, patronymic, specialization_id) VALUES ('Борис', 'Борисов', 'Борисович', 2);
INSERT INTO PUBLIC.doctor(name, surname, patronymic, specialization_id) VALUES ('Оксана', 'Оксанова', 'Олеговна', 3);
INSERT INTO PUBLIC.doctor(name, surname, patronymic, specialization_id) VALUES ('Дарья', 'Дарьева', 'Борисовна', 4);
INSERT INTO PUBLIC.patient(name, surname, patronymic, phone_number) VALUES ('Ксения', 'Юрьева', '', '892788881118');
INSERT INTO PUBLIC.patient(name, surname, patronymic, phone_number) VALUES ('Ксения', 'Валерьева', 'Олеговна', '892777781118');
INSERT INTO PUBLIC.patient(name, surname, patronymic, phone_number) VALUES ('Илон', 'Маск', 'Иванович', '892766671118');
INSERT INTO PUBLIC.patient(name, surname, patronymic, phone_number) VALUES ('Марк', 'Марков', 'Маркович', '892722221118');
INSERT INTO PUBLIC.patient(name, surname, patronymic, phone_number) VALUES ('Егор', 'Егоров', '', '892785431118');
INSERT INTO PUBLIC.priority(name) VALUES ('Нормальный');
INSERT INTO PUBLIC.priority(name) VALUES ('Cрочный');
INSERT INTO PUBLIC.priority(name) VALUES ('Немедленный');
INSERT INTO PUBLIC.recipe(description, patient_id, doctor_id, creation_date, expiration_date, priority_id) VALUES ('Мезим', 0, 0, SYSDATE, SYSDATE, 0);
INSERT INTO PUBLIC.recipe(description, patient_id, doctor_id, creation_date, expiration_date, priority_id) VALUES ('Антигрипин', 1, 1, SYSDATE, SYSDATE, 1);
INSERT INTO PUBLIC.recipe(description, patient_id, doctor_id, creation_date, expiration_date, priority_id) VALUES ('Тестер', 2, 2, SYSDATE, SYSDATE, 2);
INSERT INTO PUBLIC.recipe(description, patient_id, doctor_id, creation_date, expiration_date, priority_id) VALUES ('Иммунитет плюс', 3, 3, SYSDATE, SYSDATE, 0);
INSERT INTO PUBLIC.recipe(description, patient_id, doctor_id, creation_date, expiration_date, priority_id) VALUES ('Достойный препарат', 4, 4, SYSDATE, SYSDATE, 1);